name: Version Update

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update_version:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, '[release]') || contains(github.event.pull_request.title, '[Release]')

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Process PR Description for Changelog
      id: process_description
      run: |
        echo "${{ github.event.pull_request.title }}" > pr_title.txt
        echo "${{ github.event.pull_request.body }}" > pr_description.txt
        
        # Extract checklist items from PR description if they exist
        if grep -q "\- \[x\]" pr_description.txt; then
          grep "\- \[x\]" pr_description.txt | sed "s/- \[x\]/\-/g" > pr_changes.txt
          echo "Using checklist items from PR description for changelog"
        else
          echo "${{ github.event.pull_request.title }}" | sed "s/\[release\]//i" | sed "s/^\s*//" > pr_changes.txt
          echo "Using PR title for changelog"
        fi
        
        # Create the diff file for analysis
        git log --pretty=format:"%s" origin/${{ github.base_ref }}..origin/${{ github.head_ref }} >> pr_changes.txt
        git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }} > pr_diff.txt
    
    - name: Run version update script
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: python scripts/version_update.py
    
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # Only add the specific files we want to commit
        git add changelog.md changelog.txt hostinger-affiliate-plugin.php
        git commit -m "Update version and changelog [skip ci]" || echo "No changes to commit"
        git push
        
    - name: Cleanup temporary files
      if: always()
      run: |
        rm -f pr_title.txt pr_description.txt pr_changes.txt pr_diff.txt 