name: Version Update

on:
  pull_request:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, '[release]') || contains(github.event.pull_request.title, '[Release]')

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Prepare PR Information
      run: |
        echo "${{ github.event.pull_request.title }}" > pr_title.txt
        echo "${{ github.event.pull_request.body }}" > pr_description.txt
        git log --pretty=format:"%s" origin/${{ github.base_ref }}..origin/${{ github.head_ref }} > pr_changes.txt
        git diff origin/${{ github.base_ref }}..origin/${{ github.head_ref }} > pr_diff.txt
    
    - name: Run version update script
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: python scripts/version_update.py
    
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update version and changelog [skip ci]" || echo "No changes to commit"
        git push 